version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@0.2.3
  
  
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            source devops/bin/activate
            make lint
  
          no_output_timeout: 30m 
          
  configure-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, Test and Upload docker image
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PWD}
            docker build -t dockerbeginnersiva/project6:2.0 .
            docker run -d --rm --name flaskapp -p 8081:8080 dockerbeginnersiva/project6:2.0
            sleep 5
            docker container ls
            export URL="http://localhost:8081"
            export response=$(curl -s $URL)
            echo "This is response $response"
            if [[ $response == *"Sivakumar"* ]]; then
              docker stop flaskapp
            else
              docker stop flaskapp
              exit 1
            fi
            docker push dockerbeginnersiva/project6:2.0
            
  install-eks:
    machine: true
    steps:
      - checkout
      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
              echo "eksctl is already installed"
              exit 0
            fi
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download

            
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          siva-capstone-deployment 
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yaml
          resource-name: deployment/siva-capstone-deployment 

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          siva-capstone-deployment 
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Test cluster
          command: |
            kubectl get services
            kubectl get svc
            kubectl get nodes -o wide
            kubectl get pods
            kubectl get deployment
workflows:
  deployment:
    jobs:
      - install-eks
      - lint
      - build:
          requires:
            - lint
      - aws-eks/create-cluster:
          cluster-name: siva-capstone-deployment 
          requires:
            - install-eks
      - create-deployment:
          cluster-name: siva-capstone-deployment 
          requires:
            - aws-eks/create-cluster
      - test-cluster:
          cluster-name: siva-capstone-deployment 
          requires:
            - aws-eks/create-cluster
      - aws-eks/delete-cluster:
          cluster-name: siva-capstone-deployment 
          requires:
            - test-cluster