version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@0.2.3
  
  
jobs:
  check-aws-identity:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      # - run:
      #     name: add credentials
      #     command: |
      #       mkdir ~/.aws/
      #       cat \<< EOF > ~/.aws/credentials
      #       aws_access_key_id = AKIA3BIT4IF7LGOO67SN
      #       aws_secret_access_key = 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
      #       EOF
      #       cat \<< EOF > ~/.aws/config
      #       [default]
      #       region = us-east-1
      #       EOF
      - run:
          name: aws caller identity
          command: |
            cat ~/.aws/credentials
            cat ~/.aws/config
            aws sts get-caller-identity
  create-small-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ''
      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
            echo "eksctl is already installed"
            exit 0
            fi
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
            SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download
      
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          aws-region: us-east-2
          skip-kubectl-install: false
          verbose: 3
          node-type: t2.small
          nodes-max: 2
          show-eksctl-command: true
          ssh-access: false
          ssh-public-key: ''
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            source devops/bin/activate
            make lint
  
          no_output_timeout: 30m 
          
  configure-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, Test and Upload docker image
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PWD}
            docker build -t shubham241/capstone .
            docker run -d --rm --name testapp -p 8081:8080 shubham241/capstone
            sleep 5
            docker container ls
            export URL="http://localhost:8081"
            export response=$(curl -s $URL)
            echo "This is response $response"
            if [[ $response == *"Shubham"* ]]; then
              docker stop testapp
            else
              docker stop testapp
              exit 1
            fi
            docker push shubham241/capstone
            
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Kube cluster
          command: |
            kubectl get services
            
            
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string

    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/shubham-capstone-deployment
          
          
  test-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Kube cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment

          
workflows:
  default:
    jobs:
      - lint
      # - check-aws-identity
      - configure-image:
          requires:
            - lint
      # - create-small-cluster:
      #    cluster-name: shubham-capstone-${CIRCLE_WORKFLOW_ID:0:7}
      #    requires:
      #      - configure-image
      # - test-cluster:
      #     cluster-name: shubham-capstone-${CIRCLE_WORKFLOW_ID:0:7}
      #     requires:
      #      - create-small-cluster
      
      - create-deployment:
          cluster-name: shubham-capstone-1addc91
          requires:
           - configure-image
      - test-deployment:
          cluster-name: shubham-capstone-1addc91
          requires:
            - create-deployment              
      - aws-eks/update-container-image:
          cluster-name: shubham-capstone-1addc91
          container-image-updates: 'shubham-capstone-deployment=shubham241/capstone'
          get-rollout-status: true
          record: true
          requires:
           - test-deployment
          resource-name: deployment/shubham-capstone-deployment        
          
            
            
#      - aws-eks/delete-cluster:
#          cluster-name: siva-capstone
#          requires:
#            - aws-eks/update-container-image
